@tool
class_name ActionReference
extends RefCounted
## Builds the Action Reference (docs/action-reference.md) from the built-in
## actions: each action's parameters come from its [code]run[/code] method
## and its description from the action script's [code]##[/code] comment.
## [codeblock]
## godot --headless --path . -s res://addons/storyteller/editor/write_action_reference.gd
## [/codeblock]
## A test fails when the file in the repository no longer matches, so the
## reference stays current.

const PATH := "res://docs/action-reference.md"


## The whole reference as Markdown.
static func build() -> String:
	var entries := []
	for script: Script in TaleDirector.BUILTIN_ACTIONS:
		var action: TaleAction = script.new()
		entries.append({"name": action.get_action_name(), "script": script})
	entries.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return a["name"] < b["name"])
	var lines := PackedStringArray([
		"# Action Reference",
		"",
		"Every built-in action a tale can call, generated from the action scripts in `addons/storyteller/actions/` by `addons/storyteller/editor/action_reference.gd`. Do not edit this file by hand; change the action's `##` comment and run `addons/storyteller/editor/write_action_reference.gd`.",
		"",
		"Arguments can be given by position or by name: `backdrop(\"night\", time = 2.0)`. Actions that take time can be awaited, `await wait(1.0)`, to hold the tale until they finish. Cast member and camera methods are listed in §13 of the [TaleScript specification](talescript-spec.md).",
		"",
	])
	var names := PackedStringArray()
	for entry in entries:
		names.append("[`%s`](#%s)" % [entry["name"], entry["name"].replace("_", "-")])
	lines.append("Actions: " + ", ".join(names) + ".")
	for entry in entries:
		lines.append("")
		lines.append_array(_section(entry["name"], entry["script"]))
	return "\n".join(lines) + "\n"


## Writes [method build] to [param path]. Returns OK or an error.
static func write(path := PATH) -> Error:
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		return FileAccess.get_open_error()
	file.store_string(build())
	file.close()
	return OK


static func _section(action_name: String, script: Script) -> PackedStringArray:
	var params := TaleCalls.parameters(script, "run", 1)
	var signature := PackedStringArray()
	for param in params:
		signature.append(param["name"] if param["required"] else "%s = %s" % [param["name"], _value_source(param["default"])])
	var lines := PackedStringArray(["## %s" % action_name, "", "```gdscript", "%s(%s)" % [action_name, ", ".join(signature)], "```", ""])
	lines.append(_description(script, action_name))
	if not params.is_empty():
		lines.append("")
		lines.append("| Parameter | Type | Default |")
		lines.append("|---|---|---|")
		for param in params:
			var type_name := "any" if param["type"] == TYPE_NIL else type_string(param["type"])
			lines.append("| `%s` | %s | %s |" % [param["name"], type_name, "required" if param["required"] else "`%s`" % _value_source(param["default"])])
	return lines


## The action script's leading [code]##[/code] comment as Markdown, without
## the signature it usually starts with.
static func _description(script: Script, action_name: String) -> String:
	var comment := PackedStringArray()
	var started := false
	for line in script.source_code.split("\n"):
		if line.begins_with("##"):
			comment.append(line.trim_prefix("##").trim_prefix(" ").trim_suffix(" "))
			started = true
		elif started or not (line.begins_with("extends") or line.strip_edges().is_empty()):
			break
	# Prose lines join into one paragraph; code blocks keep their lines.
	var text := ""
	var in_code := false
	for line in comment:
		if line.strip_edges() == "[codeblock]":
			in_code = true
			text = text.strip_edges() + "\n\n```gdscript\n"
		elif line.strip_edges() == "[/codeblock]":
			in_code = false
			text += "```\n\n"
		elif in_code:
			text += line + "\n"
		else:
			text += line.strip_edges() + " "
	text = text.strip_edges()
	if text.begins_with(action_name + "("):
		var depth := 0
		for i in text.length():
			if text[i] == "(":
				depth += 1
			elif text[i] == ")":
				depth -= 1
				if depth == 0:
					text = text.substr(i + 1).trim_prefix(":").strip_edges()
					break
	text = RegEx.create_from_string("\\[code\\](.*?)\\[/code\\]").sub(text, "`$1`", true)
	text = RegEx.create_from_string("\\[(?:signal|method|member|constant) ([^\\]]+)\\]").sub(text, "`$1`", true)
	text = RegEx.create_from_string("\\[([A-Z][A-Za-z]+)\\]").sub(text, "`$1`", true)
	return text.substr(0, 1).to_upper() + text.substr(1) if not text.is_empty() else "No description yet."


## [param value] written the way a tale would write it.
static func _value_source(value: Variant) -> String:
	match typeof(value):
		TYPE_STRING, TYPE_STRING_NAME:
			return TaleExpr.quote(str(value))
		TYPE_FLOAT:
			var text := str(value)
			return text if "." in text or "e" in text else text + ".0"
		TYPE_NIL:
			return "null"
		TYPE_COLOR:
			for constant in ["BLACK", "WHITE", "RED", "GREEN", "BLUE", "TRANSPARENT"]:
				if value == Color(constant):
					return "Color." + constant
			return "Color(%s, %s, %s, %s)" % [value.r, value.g, value.b, value.a]
		TYPE_VECTOR2:
			return "Vector2(%s, %s)" % [_value_source(value.x), _value_source(value.y)]
	return str(value)
